/*
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: api@bitly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package bitly.api.model.bitly.V4;

import java.util.Objects;
import java.util.Arrays;
import bitly.api.model.bitly.V4.BaseChannel;
import bitly.api.model.bitly.V4.BaseChannelBitlink;
import bitly.api.model.bitly.V4.ChannelModifyAllOf;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * ChannelModify
 */
@JsonPropertyOrder({
  ChannelModify.JSON_PROPERTY_GROUP_GUID,
  ChannelModify.JSON_PROPERTY_GUID,
  ChannelModify.JSON_PROPERTY_NAME,
  ChannelModify.JSON_PROPERTY_MODIFIED,
  ChannelModify.JSON_PROPERTY_CREATED,
  ChannelModify.JSON_PROPERTY_BITLINKS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-09-02T16:51:48.193+01:00[Europe/London]")
public class ChannelModify {
  public static final String JSON_PROPERTY_GROUP_GUID = "group_guid";
  private String groupGuid;

  public static final String JSON_PROPERTY_GUID = "guid";
  private String guid;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_MODIFIED = "modified";
  private String modified;

  public static final String JSON_PROPERTY_CREATED = "created";
  private String created;

  public static final String JSON_PROPERTY_BITLINKS = "bitlinks";
  private List<BaseChannelBitlink> bitlinks = null;


  public ChannelModify groupGuid(String groupGuid) {
    
    this.groupGuid = groupGuid;
    return this;
  }

   /**
   * Get groupGuid
   * @return groupGuid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_GROUP_GUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGroupGuid() {
    return groupGuid;
  }


  public void setGroupGuid(String groupGuid) {
    this.groupGuid = groupGuid;
  }


  public ChannelModify guid(String guid) {
    
    this.guid = guid;
    return this;
  }

   /**
   * Get guid
   * @return guid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_GUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGuid() {
    return guid;
  }


  public void setGuid(String guid) {
    this.guid = guid;
  }


  public ChannelModify name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public ChannelModify modified(String modified) {
    
    this.modified = modified;
    return this;
  }

   /**
   * ISO_TIMESTAMP
   * @return modified
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ISO_TIMESTAMP")
  @JsonProperty(JSON_PROPERTY_MODIFIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getModified() {
    return modified;
  }


  public void setModified(String modified) {
    this.modified = modified;
  }


  public ChannelModify created(String created) {
    
    this.created = created;
    return this;
  }

   /**
   * ISO TIMESTAMP
   * @return created
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ISO TIMESTAMP")
  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreated() {
    return created;
  }


  public void setCreated(String created) {
    this.created = created;
  }


  public ChannelModify bitlinks(List<BaseChannelBitlink> bitlinks) {
    
    this.bitlinks = bitlinks;
    return this;
  }

  public ChannelModify addBitlinksItem(BaseChannelBitlink bitlinksItem) {
    if (this.bitlinks == null) {
      this.bitlinks = new ArrayList<BaseChannelBitlink>();
    }
    this.bitlinks.add(bitlinksItem);
    return this;
  }

   /**
   * Get bitlinks
   * @return bitlinks
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_BITLINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<BaseChannelBitlink> getBitlinks() {
    return bitlinks;
  }


  public void setBitlinks(List<BaseChannelBitlink> bitlinks) {
    this.bitlinks = bitlinks;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChannelModify channelModify = (ChannelModify) o;
    return Objects.equals(this.groupGuid, channelModify.groupGuid) &&
        Objects.equals(this.guid, channelModify.guid) &&
        Objects.equals(this.name, channelModify.name) &&
        Objects.equals(this.modified, channelModify.modified) &&
        Objects.equals(this.created, channelModify.created) &&
        Objects.equals(this.bitlinks, channelModify.bitlinks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(groupGuid, guid, name, modified, created, bitlinks);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChannelModify {\n");
    sb.append("    groupGuid: ").append(toIndentedString(groupGuid)).append("\n");
    sb.append("    guid: ").append(toIndentedString(guid)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    bitlinks: ").append(toIndentedString(bitlinks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

