/*
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: api@bitly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package bitly.api.model.bitly.V4;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * ConsumableFeature
 */
@JsonPropertyOrder({
  ConsumableFeature.JSON_PROPERTY_NAME,
  ConsumableFeature.JSON_PROPERTY_CREATED,
  ConsumableFeature.JSON_PROPERTY_MODIFIED,
  ConsumableFeature.JSON_PROPERTY_LIMIT,
  ConsumableFeature.JSON_PROPERTY_IS_TIER_DEFAULT,
  ConsumableFeature.JSON_PROPERTY_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-09-02T16:51:48.193+01:00[Europe/London]")
public class ConsumableFeature {
  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_CREATED = "created";
  private String created;

  public static final String JSON_PROPERTY_MODIFIED = "modified";
  private String modified;

  public static final String JSON_PROPERTY_LIMIT = "limit";
  private Integer limit;

  public static final String JSON_PROPERTY_IS_TIER_DEFAULT = "is_tier_default";
  private Boolean isTierDefault;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;


  public ConsumableFeature name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public ConsumableFeature created(String created) {
    
    this.created = created;
    return this;
  }

   /**
   * ISO_TIMESTAMP
   * @return created
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ISO_TIMESTAMP")
  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreated() {
    return created;
  }


  public void setCreated(String created) {
    this.created = created;
  }


  public ConsumableFeature modified(String modified) {
    
    this.modified = modified;
    return this;
  }

   /**
   * ISO_TIMESTAMP
   * @return modified
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ISO_TIMESTAMP")
  @JsonProperty(JSON_PROPERTY_MODIFIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getModified() {
    return modified;
  }


  public void setModified(String modified) {
    this.modified = modified;
  }


  public ConsumableFeature limit(Integer limit) {
    
    this.limit = limit;
    return this;
  }

   /**
   * Get limit
   * @return limit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LIMIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getLimit() {
    return limit;
  }


  public void setLimit(Integer limit) {
    this.limit = limit;
  }


  public ConsumableFeature isTierDefault(Boolean isTierDefault) {
    
    this.isTierDefault = isTierDefault;
    return this;
  }

   /**
   * Get isTierDefault
   * @return isTierDefault
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_IS_TIER_DEFAULT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsTierDefault() {
    return isTierDefault;
  }


  public void setIsTierDefault(Boolean isTierDefault) {
    this.isTierDefault = isTierDefault;
  }


  public ConsumableFeature id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConsumableFeature consumableFeature = (ConsumableFeature) o;
    return Objects.equals(this.name, consumableFeature.name) &&
        Objects.equals(this.created, consumableFeature.created) &&
        Objects.equals(this.modified, consumableFeature.modified) &&
        Objects.equals(this.limit, consumableFeature.limit) &&
        Objects.equals(this.isTierDefault, consumableFeature.isTierDefault) &&
        Objects.equals(this.id, consumableFeature.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, created, modified, limit, isTierDefault, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConsumableFeature {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    isTierDefault: ").append(toIndentedString(isTierDefault)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

