/*
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: api@bitly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package bitly.api.model.bitly.V4;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * CreatePaymentMethod
 */
@JsonPropertyOrder({
  CreatePaymentMethod.JSON_PROPERTY_STRIPE_TOKEN
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-09-02T16:51:48.193+01:00[Europe/London]")
public class CreatePaymentMethod {
  public static final String JSON_PROPERTY_STRIPE_TOKEN = "stripe_token";
  private String stripeToken;


  public CreatePaymentMethod stripeToken(String stripeToken) {
    
    this.stripeToken = stripeToken;
    return this;
  }

   /**
   * Get stripeToken
   * @return stripeToken
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STRIPE_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStripeToken() {
    return stripeToken;
  }


  public void setStripeToken(String stripeToken) {
    this.stripeToken = stripeToken;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreatePaymentMethod createPaymentMethod = (CreatePaymentMethod) o;
    return Objects.equals(this.stripeToken, createPaymentMethod.stripeToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(stripeToken);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreatePaymentMethod {\n");
    sb.append("    stripeToken: ").append(toIndentedString(stripeToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

