/*
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: api@bitly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package bitly.api.model.bitly.V4;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Event
 */
@JsonPropertyOrder({
  Event.JSON_PROPERTY_UI_ACTION,
  Event.JSON_PROPERTY_REFERRER,
  Event.JSON_PROPERTY_ACTION,
  Event.JSON_PROPERTY_INITIATED_BY,
  Event.JSON_PROPERTY_GROUP_GUID,
  Event.JSON_PROPERTY_UI_ACTION_DATE,
  Event.JSON_PROPERTY_LOGIN,
  Event.JSON_PROPERTY_ORG_GUID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-09-02T16:51:48.193+01:00[Europe/London]")
public class Event {
  public static final String JSON_PROPERTY_UI_ACTION = "ui_action";
  private String uiAction;

  public static final String JSON_PROPERTY_REFERRER = "referrer";
  private String referrer;

  public static final String JSON_PROPERTY_ACTION = "action";
  private String action;

  /**
   * Gets or Sets initiatedBy
   */
  public enum InitiatedByEnum {
    APP("app"),
    
    USER("user");

    private String value;

    InitiatedByEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static InitiatedByEnum fromValue(String value) {
      for (InitiatedByEnum b : InitiatedByEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_INITIATED_BY = "initiated_by";
  private InitiatedByEnum initiatedBy;

  public static final String JSON_PROPERTY_GROUP_GUID = "group_guid";
  private String groupGuid;

  public static final String JSON_PROPERTY_UI_ACTION_DATE = "ui_action_date";
  private String uiActionDate;

  public static final String JSON_PROPERTY_LOGIN = "login";
  private String login;

  public static final String JSON_PROPERTY_ORG_GUID = "org_guid";
  private String orgGuid;


  public Event uiAction(String uiAction) {
    
    this.uiAction = uiAction;
    return this;
  }

   /**
   * Get uiAction
   * @return uiAction
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_UI_ACTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUiAction() {
    return uiAction;
  }


  public void setUiAction(String uiAction) {
    this.uiAction = uiAction;
  }


  public Event referrer(String referrer) {
    
    this.referrer = referrer;
    return this;
  }

   /**
   * Get referrer
   * @return referrer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REFERRER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReferrer() {
    return referrer;
  }


  public void setReferrer(String referrer) {
    this.referrer = referrer;
  }


  public Event action(String action) {
    
    this.action = action;
    return this;
  }

   /**
   * Get action
   * @return action
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ACTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAction() {
    return action;
  }


  public void setAction(String action) {
    this.action = action;
  }


  public Event initiatedBy(InitiatedByEnum initiatedBy) {
    
    this.initiatedBy = initiatedBy;
    return this;
  }

   /**
   * Get initiatedBy
   * @return initiatedBy
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_INITIATED_BY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public InitiatedByEnum getInitiatedBy() {
    return initiatedBy;
  }


  public void setInitiatedBy(InitiatedByEnum initiatedBy) {
    this.initiatedBy = initiatedBy;
  }


  public Event groupGuid(String groupGuid) {
    
    this.groupGuid = groupGuid;
    return this;
  }

   /**
   * Get groupGuid
   * @return groupGuid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_GROUP_GUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGroupGuid() {
    return groupGuid;
  }


  public void setGroupGuid(String groupGuid) {
    this.groupGuid = groupGuid;
  }


  public Event uiActionDate(String uiActionDate) {
    
    this.uiActionDate = uiActionDate;
    return this;
  }

   /**
   * Get uiActionDate
   * @return uiActionDate
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_UI_ACTION_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUiActionDate() {
    return uiActionDate;
  }


  public void setUiActionDate(String uiActionDate) {
    this.uiActionDate = uiActionDate;
  }


  public Event login(String login) {
    
    this.login = login;
    return this;
  }

   /**
   * Get login
   * @return login
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_LOGIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLogin() {
    return login;
  }


  public void setLogin(String login) {
    this.login = login;
  }


  public Event orgGuid(String orgGuid) {
    
    this.orgGuid = orgGuid;
    return this;
  }

   /**
   * Get orgGuid
   * @return orgGuid
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ORG_GUID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getOrgGuid() {
    return orgGuid;
  }


  public void setOrgGuid(String orgGuid) {
    this.orgGuid = orgGuid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Event event = (Event) o;
    return Objects.equals(this.uiAction, event.uiAction) &&
        Objects.equals(this.referrer, event.referrer) &&
        Objects.equals(this.action, event.action) &&
        Objects.equals(this.initiatedBy, event.initiatedBy) &&
        Objects.equals(this.groupGuid, event.groupGuid) &&
        Objects.equals(this.uiActionDate, event.uiActionDate) &&
        Objects.equals(this.login, event.login) &&
        Objects.equals(this.orgGuid, event.orgGuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uiAction, referrer, action, initiatedBy, groupGuid, uiActionDate, login, orgGuid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Event {\n");
    sb.append("    uiAction: ").append(toIndentedString(uiAction)).append("\n");
    sb.append("    referrer: ").append(toIndentedString(referrer)).append("\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    initiatedBy: ").append(toIndentedString(initiatedBy)).append("\n");
    sb.append("    groupGuid: ").append(toIndentedString(groupGuid)).append("\n");
    sb.append("    uiActionDate: ").append(toIndentedString(uiActionDate)).append("\n");
    sb.append("    login: ").append(toIndentedString(login)).append("\n");
    sb.append("    orgGuid: ").append(toIndentedString(orgGuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

