/*
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: api@bitly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package bitly.api.model.bitly.V4;

import java.util.Objects;
import java.util.Arrays;
import bitly.api.model.bitly.V4.ShareAccount;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * ShareAccounts
 */
@JsonPropertyOrder({
  ShareAccounts.JSON_PROPERTY_SHARE_ACCOUNTS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-09-02T16:51:48.193+01:00[Europe/London]")
public class ShareAccounts {
  public static final String JSON_PROPERTY_SHARE_ACCOUNTS = "share_accounts";
  private List<ShareAccount> shareAccounts = null;


  public ShareAccounts shareAccounts(List<ShareAccount> shareAccounts) {
    
    this.shareAccounts = shareAccounts;
    return this;
  }

  public ShareAccounts addShareAccountsItem(ShareAccount shareAccountsItem) {
    if (this.shareAccounts == null) {
      this.shareAccounts = new ArrayList<ShareAccount>();
    }
    this.shareAccounts.add(shareAccountsItem);
    return this;
  }

   /**
   * Get shareAccounts
   * @return shareAccounts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SHARE_ACCOUNTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ShareAccount> getShareAccounts() {
    return shareAccounts;
  }


  public void setShareAccounts(List<ShareAccount> shareAccounts) {
    this.shareAccounts = shareAccounts;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShareAccounts shareAccounts = (ShareAccounts) o;
    return Objects.equals(this.shareAccounts, shareAccounts.shareAccounts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shareAccounts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShareAccounts {\n");
    sb.append("    shareAccounts: ").append(toIndentedString(shareAccounts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

