/*
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: api@bitly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bitly.model.V4;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * AddCustomBitlink
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-09-07T02:24:01.569+01:00[Europe/London]")
public class AddCustomBitlink {
  public static final String SERIALIZED_NAME_BITLINK_ID = "bitlink_id";
  @SerializedName(SERIALIZED_NAME_BITLINK_ID)
  private String bitlinkId;

  public static final String SERIALIZED_NAME_CUSTOM_BITLINK = "custom_bitlink";
  @SerializedName(SERIALIZED_NAME_CUSTOM_BITLINK)
  private String customBitlink;


  public AddCustomBitlink bitlinkId(String bitlinkId) {
    
    this.bitlinkId = bitlinkId;
    return this;
  }

   /**
   * Get bitlinkId
   * @return bitlinkId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getBitlinkId() {
    return bitlinkId;
  }


  public void setBitlinkId(String bitlinkId) {
    this.bitlinkId = bitlinkId;
  }


  public AddCustomBitlink customBitlink(String customBitlink) {
    
    this.customBitlink = customBitlink;
    return this;
  }

   /**
   * Get customBitlink
   * @return customBitlink
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCustomBitlink() {
    return customBitlink;
  }


  public void setCustomBitlink(String customBitlink) {
    this.customBitlink = customBitlink;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddCustomBitlink addCustomBitlink = (AddCustomBitlink) o;
    return Objects.equals(this.bitlinkId, addCustomBitlink.bitlinkId) &&
        Objects.equals(this.customBitlink, addCustomBitlink.customBitlink);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bitlinkId, customBitlink);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddCustomBitlink {\n");
    sb.append("    bitlinkId: ").append(toIndentedString(bitlinkId)).append("\n");
    sb.append("    customBitlink: ").append(toIndentedString(customBitlink)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

