/*
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: api@bitly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bitly.model.V4;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * AppAssociationDetail
 */
@JsonPropertyOrder({
  AppAssociationDetail.JSON_PROPERTY_PRIORITY,
  AppAssociationDetail.JSON_PROPERTY_FALLBACK,
  AppAssociationDetail.JSON_PROPERTY_APP_GUID,
  AppAssociationDetail.JSON_PROPERTY_OS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-09-03T23:35:21.555+01:00[Europe/London]")
public class AppAssociationDetail {
  public static final String JSON_PROPERTY_PRIORITY = "priority";
  private Integer priority;

  public static final String JSON_PROPERTY_FALLBACK = "fallback";
  private Boolean fallback;

  public static final String JSON_PROPERTY_APP_GUID = "app_guid";
  private String appGuid;

  public static final String JSON_PROPERTY_OS = "os";
  private String os;


  public AppAssociationDetail priority(Integer priority) {
    
    this.priority = priority;
    return this;
  }

   /**
   * Get priority
   * @return priority
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PRIORITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPriority() {
    return priority;
  }


  public void setPriority(Integer priority) {
    this.priority = priority;
  }


  public AppAssociationDetail fallback(Boolean fallback) {
    
    this.fallback = fallback;
    return this;
  }

   /**
   * Get fallback
   * @return fallback
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FALLBACK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getFallback() {
    return fallback;
  }


  public void setFallback(Boolean fallback) {
    this.fallback = fallback;
  }


  public AppAssociationDetail appGuid(String appGuid) {
    
    this.appGuid = appGuid;
    return this;
  }

   /**
   * Get appGuid
   * @return appGuid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_APP_GUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAppGuid() {
    return appGuid;
  }


  public void setAppGuid(String appGuid) {
    this.appGuid = appGuid;
  }


  public AppAssociationDetail os(String os) {
    
    this.os = os;
    return this;
  }

   /**
   * Get os
   * @return os
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_OS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOs() {
    return os;
  }


  public void setOs(String os) {
    this.os = os;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppAssociationDetail appAssociationDetail = (AppAssociationDetail) o;
    return Objects.equals(this.priority, appAssociationDetail.priority) &&
        Objects.equals(this.fallback, appAssociationDetail.fallback) &&
        Objects.equals(this.appGuid, appAssociationDetail.appGuid) &&
        Objects.equals(this.os, appAssociationDetail.os);
  }

  @Override
  public int hashCode() {
    return Objects.hash(priority, fallback, appGuid, os);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppAssociationDetail {\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    fallback: ").append(toIndentedString(fallback)).append("\n");
    sb.append("    appGuid: ").append(toIndentedString(appGuid)).append("\n");
    sb.append("    os: ").append(toIndentedString(os)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

