/*
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: api@bitly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bitly.model.V4;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * BillingDowngrade
 */
@JsonPropertyOrder({
  BillingDowngrade.JSON_PROPERTY_GROUP_GUIDS,
  BillingDowngrade.JSON_PROPERTY_TIER_NAME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-09-03T23:35:21.555+01:00[Europe/London]")
public class BillingDowngrade {
  public static final String JSON_PROPERTY_GROUP_GUIDS = "group_guids";
  private List<String> groupGuids = null;

  public static final String JSON_PROPERTY_TIER_NAME = "tier_name";
  private String tierName;


  public BillingDowngrade groupGuids(List<String> groupGuids) {
    
    this.groupGuids = groupGuids;
    return this;
  }

  public BillingDowngrade addGroupGuidsItem(String groupGuidsItem) {
    if (this.groupGuids == null) {
      this.groupGuids = new ArrayList<String>();
    }
    this.groupGuids.add(groupGuidsItem);
    return this;
  }

   /**
   * Get groupGuids
   * @return groupGuids
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_GROUP_GUIDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getGroupGuids() {
    return groupGuids;
  }


  public void setGroupGuids(List<String> groupGuids) {
    this.groupGuids = groupGuids;
  }


  public BillingDowngrade tierName(String tierName) {
    
    this.tierName = tierName;
    return this;
  }

   /**
   * Get tierName
   * @return tierName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TIER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTierName() {
    return tierName;
  }


  public void setTierName(String tierName) {
    this.tierName = tierName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BillingDowngrade billingDowngrade = (BillingDowngrade) o;
    return Objects.equals(this.groupGuids, billingDowngrade.groupGuids) &&
        Objects.equals(this.tierName, billingDowngrade.tierName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(groupGuids, tierName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BillingDowngrade {\n");
    sb.append("    groupGuids: ").append(toIndentedString(groupGuids)).append("\n");
    sb.append("    tierName: ").append(toIndentedString(tierName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

