/*
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: api@bitly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bitly.model.V4;

import java.util.Objects;
import java.util.Arrays;
import com.bitly.model.V4.DeeplinkRule;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * BitlinkUpdate
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-09-07T02:24:01.569+01:00[Europe/London]")
public class BitlinkUpdate {
  public static final String SERIALIZED_NAME_ARCHIVED = "archived";
  @SerializedName(SERIALIZED_NAME_ARCHIVED)
  private Boolean archived;

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  private List<String> tags = null;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private String createdAt;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private String title;

  public static final String SERIALIZED_NAME_DEEPLINKS = "deeplinks";
  @SerializedName(SERIALIZED_NAME_DEEPLINKS)
  private List<DeeplinkRule> deeplinks = null;

  public static final String SERIALIZED_NAME_CREATED_BY = "created_by";
  @SerializedName(SERIALIZED_NAME_CREATED_BY)
  private String createdBy;

  public static final String SERIALIZED_NAME_LONG_URL = "long_url";
  @SerializedName(SERIALIZED_NAME_LONG_URL)
  private String longUrl;

  public static final String SERIALIZED_NAME_CLIENT_ID = "client_id";
  @SerializedName(SERIALIZED_NAME_CLIENT_ID)
  private String clientId;

  public static final String SERIALIZED_NAME_CUSTOM_BITLINKS = "custom_bitlinks";
  @SerializedName(SERIALIZED_NAME_CUSTOM_BITLINKS)
  private List<String> customBitlinks = null;

  public static final String SERIALIZED_NAME_LINK = "link";
  @SerializedName(SERIALIZED_NAME_LINK)
  private String link;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;


  public BitlinkUpdate archived(Boolean archived) {
    
    this.archived = archived;
    return this;
  }

   /**
   * Get archived
   * @return archived
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getArchived() {
    return archived;
  }


  public void setArchived(Boolean archived) {
    this.archived = archived;
  }


  public BitlinkUpdate tags(List<String> tags) {
    
    this.tags = tags;
    return this;
  }

  public BitlinkUpdate addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<String>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getTags() {
    return tags;
  }


  public void setTags(List<String> tags) {
    this.tags = tags;
  }


  public BitlinkUpdate createdAt(String createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }


  public BitlinkUpdate title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTitle() {
    return title;
  }


  public void setTitle(String title) {
    this.title = title;
  }


  public BitlinkUpdate deeplinks(List<DeeplinkRule> deeplinks) {
    
    this.deeplinks = deeplinks;
    return this;
  }

  public BitlinkUpdate addDeeplinksItem(DeeplinkRule deeplinksItem) {
    if (this.deeplinks == null) {
      this.deeplinks = new ArrayList<DeeplinkRule>();
    }
    this.deeplinks.add(deeplinksItem);
    return this;
  }

   /**
   * Get deeplinks
   * @return deeplinks
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<DeeplinkRule> getDeeplinks() {
    return deeplinks;
  }


  public void setDeeplinks(List<DeeplinkRule> deeplinks) {
    this.deeplinks = deeplinks;
  }


  public BitlinkUpdate createdBy(String createdBy) {
    
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCreatedBy() {
    return createdBy;
  }


  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }


  public BitlinkUpdate longUrl(String longUrl) {
    
    this.longUrl = longUrl;
    return this;
  }

   /**
   * Get longUrl
   * @return longUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLongUrl() {
    return longUrl;
  }


  public void setLongUrl(String longUrl) {
    this.longUrl = longUrl;
  }


  public BitlinkUpdate clientId(String clientId) {
    
    this.clientId = clientId;
    return this;
  }

   /**
   * Get clientId
   * @return clientId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getClientId() {
    return clientId;
  }


  public void setClientId(String clientId) {
    this.clientId = clientId;
  }


  public BitlinkUpdate customBitlinks(List<String> customBitlinks) {
    
    this.customBitlinks = customBitlinks;
    return this;
  }

  public BitlinkUpdate addCustomBitlinksItem(String customBitlinksItem) {
    if (this.customBitlinks == null) {
      this.customBitlinks = new ArrayList<String>();
    }
    this.customBitlinks.add(customBitlinksItem);
    return this;
  }

   /**
   * Get customBitlinks
   * @return customBitlinks
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getCustomBitlinks() {
    return customBitlinks;
  }


  public void setCustomBitlinks(List<String> customBitlinks) {
    this.customBitlinks = customBitlinks;
  }


  public BitlinkUpdate link(String link) {
    
    this.link = link;
    return this;
  }

   /**
   * Get link
   * @return link
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLink() {
    return link;
  }


  public void setLink(String link) {
    this.link = link;
  }


  public BitlinkUpdate id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BitlinkUpdate bitlinkUpdate = (BitlinkUpdate) o;
    return Objects.equals(this.archived, bitlinkUpdate.archived) &&
        Objects.equals(this.tags, bitlinkUpdate.tags) &&
        Objects.equals(this.createdAt, bitlinkUpdate.createdAt) &&
        Objects.equals(this.title, bitlinkUpdate.title) &&
        Objects.equals(this.deeplinks, bitlinkUpdate.deeplinks) &&
        Objects.equals(this.createdBy, bitlinkUpdate.createdBy) &&
        Objects.equals(this.longUrl, bitlinkUpdate.longUrl) &&
        Objects.equals(this.clientId, bitlinkUpdate.clientId) &&
        Objects.equals(this.customBitlinks, bitlinkUpdate.customBitlinks) &&
        Objects.equals(this.link, bitlinkUpdate.link) &&
        Objects.equals(this.id, bitlinkUpdate.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(archived, tags, createdAt, title, deeplinks, createdBy, longUrl, clientId, customBitlinks, link, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BitlinkUpdate {\n");
    sb.append("    archived: ").append(toIndentedString(archived)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    deeplinks: ").append(toIndentedString(deeplinks)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    longUrl: ").append(toIndentedString(longUrl)).append("\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    customBitlinks: ").append(toIndentedString(customBitlinks)).append("\n");
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

