/*
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: api@bitly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bitly.model.V4;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * DeeplinkRule
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-09-07T02:24:01.569+01:00[Europe/London]")
public class DeeplinkRule {
  public static final String SERIALIZED_NAME_BITLINK = "bitlink";
  @SerializedName(SERIALIZED_NAME_BITLINK)
  private String bitlink;

  public static final String SERIALIZED_NAME_INSTALL_URL = "install_url";
  @SerializedName(SERIALIZED_NAME_INSTALL_URL)
  private String installUrl;

  public static final String SERIALIZED_NAME_CREATED = "created";
  @SerializedName(SERIALIZED_NAME_CREATED)
  private String created;

  public static final String SERIALIZED_NAME_APP_URI_PATH = "app_uri_path";
  @SerializedName(SERIALIZED_NAME_APP_URI_PATH)
  private String appUriPath;

  public static final String SERIALIZED_NAME_MODIFIED = "modified";
  @SerializedName(SERIALIZED_NAME_MODIFIED)
  private String modified;

  public static final String SERIALIZED_NAME_INSTALL_TYPE = "install_type";
  @SerializedName(SERIALIZED_NAME_INSTALL_TYPE)
  private String installType;

  public static final String SERIALIZED_NAME_APP_GUID = "app_guid";
  @SerializedName(SERIALIZED_NAME_APP_GUID)
  private String appGuid;

  public static final String SERIALIZED_NAME_GUID = "guid";
  @SerializedName(SERIALIZED_NAME_GUID)
  private String guid;

  public static final String SERIALIZED_NAME_OS = "os";
  @SerializedName(SERIALIZED_NAME_OS)
  private String os;

  public static final String SERIALIZED_NAME_BRAND_GUID = "brand_guid";
  @SerializedName(SERIALIZED_NAME_BRAND_GUID)
  private String brandGuid;


  public DeeplinkRule bitlink(String bitlink) {
    
    this.bitlink = bitlink;
    return this;
  }

   /**
   * Get bitlink
   * @return bitlink
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getBitlink() {
    return bitlink;
  }


  public void setBitlink(String bitlink) {
    this.bitlink = bitlink;
  }


  public DeeplinkRule installUrl(String installUrl) {
    
    this.installUrl = installUrl;
    return this;
  }

   /**
   * Get installUrl
   * @return installUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getInstallUrl() {
    return installUrl;
  }


  public void setInstallUrl(String installUrl) {
    this.installUrl = installUrl;
  }


  public DeeplinkRule created(String created) {
    
    this.created = created;
    return this;
  }

   /**
   * ISO timestamp
   * @return created
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ISO timestamp")

  public String getCreated() {
    return created;
  }


  public void setCreated(String created) {
    this.created = created;
  }


  public DeeplinkRule appUriPath(String appUriPath) {
    
    this.appUriPath = appUriPath;
    return this;
  }

   /**
   * Get appUriPath
   * @return appUriPath
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAppUriPath() {
    return appUriPath;
  }


  public void setAppUriPath(String appUriPath) {
    this.appUriPath = appUriPath;
  }


  public DeeplinkRule modified(String modified) {
    
    this.modified = modified;
    return this;
  }

   /**
   * ISO timestamp
   * @return modified
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ISO timestamp")

  public String getModified() {
    return modified;
  }


  public void setModified(String modified) {
    this.modified = modified;
  }


  public DeeplinkRule installType(String installType) {
    
    this.installType = installType;
    return this;
  }

   /**
   * Get installType
   * @return installType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getInstallType() {
    return installType;
  }


  public void setInstallType(String installType) {
    this.installType = installType;
  }


  public DeeplinkRule appGuid(String appGuid) {
    
    this.appGuid = appGuid;
    return this;
  }

   /**
   * Get appGuid
   * @return appGuid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAppGuid() {
    return appGuid;
  }


  public void setAppGuid(String appGuid) {
    this.appGuid = appGuid;
  }


  public DeeplinkRule guid(String guid) {
    
    this.guid = guid;
    return this;
  }

   /**
   * Get guid
   * @return guid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getGuid() {
    return guid;
  }


  public void setGuid(String guid) {
    this.guid = guid;
  }


  public DeeplinkRule os(String os) {
    
    this.os = os;
    return this;
  }

   /**
   * Get os
   * @return os
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getOs() {
    return os;
  }


  public void setOs(String os) {
    this.os = os;
  }


  public DeeplinkRule brandGuid(String brandGuid) {
    
    this.brandGuid = brandGuid;
    return this;
  }

   /**
   * Get brandGuid
   * @return brandGuid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getBrandGuid() {
    return brandGuid;
  }


  public void setBrandGuid(String brandGuid) {
    this.brandGuid = brandGuid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeeplinkRule deeplinkRule = (DeeplinkRule) o;
    return Objects.equals(this.bitlink, deeplinkRule.bitlink) &&
        Objects.equals(this.installUrl, deeplinkRule.installUrl) &&
        Objects.equals(this.created, deeplinkRule.created) &&
        Objects.equals(this.appUriPath, deeplinkRule.appUriPath) &&
        Objects.equals(this.modified, deeplinkRule.modified) &&
        Objects.equals(this.installType, deeplinkRule.installType) &&
        Objects.equals(this.appGuid, deeplinkRule.appGuid) &&
        Objects.equals(this.guid, deeplinkRule.guid) &&
        Objects.equals(this.os, deeplinkRule.os) &&
        Objects.equals(this.brandGuid, deeplinkRule.brandGuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bitlink, installUrl, created, appUriPath, modified, installType, appGuid, guid, os, brandGuid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeeplinkRule {\n");
    sb.append("    bitlink: ").append(toIndentedString(bitlink)).append("\n");
    sb.append("    installUrl: ").append(toIndentedString(installUrl)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    appUriPath: ").append(toIndentedString(appUriPath)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    installType: ").append(toIndentedString(installType)).append("\n");
    sb.append("    appGuid: ").append(toIndentedString(appGuid)).append("\n");
    sb.append("    guid: ").append(toIndentedString(guid)).append("\n");
    sb.append("    os: ").append(toIndentedString(os)).append("\n");
    sb.append("    brandGuid: ").append(toIndentedString(brandGuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

