/*
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: api@bitly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bitly.model.V4;

import java.util.Objects;
import java.util.Arrays;
import com.bitly.model.V4.AccessFeature;
import com.bitly.model.V4.ConsumableFeatureFull;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * FeatureUsage
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-09-07T02:24:01.569+01:00[Europe/London]")
public class FeatureUsage {
  public static final String SERIALIZED_NAME_CONSUMABLE_FEATURES = "consumable_features";
  @SerializedName(SERIALIZED_NAME_CONSUMABLE_FEATURES)
  private List<ConsumableFeatureFull> consumableFeatures = null;

  public static final String SERIALIZED_NAME_ACCESS_FEATURES = "access_features";
  @SerializedName(SERIALIZED_NAME_ACCESS_FEATURES)
  private List<AccessFeature> accessFeatures = null;


  public FeatureUsage consumableFeatures(List<ConsumableFeatureFull> consumableFeatures) {
    
    this.consumableFeatures = consumableFeatures;
    return this;
  }

  public FeatureUsage addConsumableFeaturesItem(ConsumableFeatureFull consumableFeaturesItem) {
    if (this.consumableFeatures == null) {
      this.consumableFeatures = new ArrayList<ConsumableFeatureFull>();
    }
    this.consumableFeatures.add(consumableFeaturesItem);
    return this;
  }

   /**
   * an array of all of the organizations consumable features
   * @return consumableFeatures
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "an array of all of the organizations consumable features")

  public List<ConsumableFeatureFull> getConsumableFeatures() {
    return consumableFeatures;
  }


  public void setConsumableFeatures(List<ConsumableFeatureFull> consumableFeatures) {
    this.consumableFeatures = consumableFeatures;
  }


  public FeatureUsage accessFeatures(List<AccessFeature> accessFeatures) {
    
    this.accessFeatures = accessFeatures;
    return this;
  }

  public FeatureUsage addAccessFeaturesItem(AccessFeature accessFeaturesItem) {
    if (this.accessFeatures == null) {
      this.accessFeatures = new ArrayList<AccessFeature>();
    }
    this.accessFeatures.add(accessFeaturesItem);
    return this;
  }

   /**
   * an array of all of the organizations access features
   * @return accessFeatures
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "an array of all of the organizations access features")

  public List<AccessFeature> getAccessFeatures() {
    return accessFeatures;
  }


  public void setAccessFeatures(List<AccessFeature> accessFeatures) {
    this.accessFeatures = accessFeatures;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FeatureUsage featureUsage = (FeatureUsage) o;
    return Objects.equals(this.consumableFeatures, featureUsage.consumableFeatures) &&
        Objects.equals(this.accessFeatures, featureUsage.accessFeatures);
  }

  @Override
  public int hashCode() {
    return Objects.hash(consumableFeatures, accessFeatures);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FeatureUsage {\n");
    sb.append("    consumableFeatures: ").append(toIndentedString(consumableFeatures)).append("\n");
    sb.append("    accessFeatures: ").append(toIndentedString(accessFeatures)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

