/*
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: api@bitly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bitly.model.V4;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Feedback
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-09-07T02:24:01.569+01:00[Europe/London]")
public class Feedback {
  public static final String SERIALIZED_NAME_SELECTION = "selection";
  @SerializedName(SERIALIZED_NAME_SELECTION)
  private String selection;

  public static final String SERIALIZED_NAME_OPTIONAL_TEXT = "optional_text";
  @SerializedName(SERIALIZED_NAME_OPTIONAL_TEXT)
  private String optionalText;


  public Feedback selection(String selection) {
    
    this.selection = selection;
    return this;
  }

   /**
   * Get selection
   * @return selection
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSelection() {
    return selection;
  }


  public void setSelection(String selection) {
    this.selection = selection;
  }


  public Feedback optionalText(String optionalText) {
    
    this.optionalText = optionalText;
    return this;
  }

   /**
   * Get optionalText
   * @return optionalText
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getOptionalText() {
    return optionalText;
  }


  public void setOptionalText(String optionalText) {
    this.optionalText = optionalText;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Feedback feedback = (Feedback) o;
    return Objects.equals(this.selection, feedback.selection) &&
        Objects.equals(this.optionalText, feedback.optionalText);
  }

  @Override
  public int hashCode() {
    return Objects.hash(selection, optionalText);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Feedback {\n");
    sb.append("    selection: ").append(toIndentedString(selection)).append("\n");
    sb.append("    optionalText: ").append(toIndentedString(optionalText)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

