/*
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: api@bitly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bitly.model.V4;

import java.util.Objects;
import java.util.Arrays;
import com.bitly.model.V4.FormPage;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * FormCapturePayload
 */
@JsonPropertyOrder({
  FormCapturePayload.JSON_PROPERTY_SUBMIT_TEXT,
  FormCapturePayload.JSON_PROPERTY_NAME,
  FormCapturePayload.JSON_PROPERTY_RESPONSE_STATUS,
  FormCapturePayload.JSON_PROPERTY_PAGES,
  FormCapturePayload.JSON_PROPERTY_VERSION,
  FormCapturePayload.JSON_PROPERTY_GROUP_GUID,
  FormCapturePayload.JSON_PROPERTY_LOGIN,
  FormCapturePayload.JSON_PROPERTY_SKIP_TEXT,
  FormCapturePayload.JSON_PROPERTY_ORG_GUID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-09-03T23:35:21.555+01:00[Europe/London]")
public class FormCapturePayload {
  public static final String JSON_PROPERTY_SUBMIT_TEXT = "submit_text";
  private String submitText;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_RESPONSE_STATUS = "response_status";
  private String responseStatus;

  public static final String JSON_PROPERTY_PAGES = "pages";
  private List<FormPage> pages = null;

  public static final String JSON_PROPERTY_VERSION = "version";
  private String version;

  public static final String JSON_PROPERTY_GROUP_GUID = "group_guid";
  private String groupGuid;

  public static final String JSON_PROPERTY_LOGIN = "login";
  private String login;

  public static final String JSON_PROPERTY_SKIP_TEXT = "skip_text";
  private String skipText;

  public static final String JSON_PROPERTY_ORG_GUID = "org_guid";
  private String orgGuid;


  public FormCapturePayload submitText(String submitText) {
    
    this.submitText = submitText;
    return this;
  }

   /**
   * Get submitText
   * @return submitText
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SUBMIT_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSubmitText() {
    return submitText;
  }


  public void setSubmitText(String submitText) {
    this.submitText = submitText;
  }


  public FormCapturePayload name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public FormCapturePayload responseStatus(String responseStatus) {
    
    this.responseStatus = responseStatus;
    return this;
  }

   /**
   * Get responseStatus
   * @return responseStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RESPONSE_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getResponseStatus() {
    return responseStatus;
  }


  public void setResponseStatus(String responseStatus) {
    this.responseStatus = responseStatus;
  }


  public FormCapturePayload pages(List<FormPage> pages) {
    
    this.pages = pages;
    return this;
  }

  public FormCapturePayload addPagesItem(FormPage pagesItem) {
    if (this.pages == null) {
      this.pages = new ArrayList<FormPage>();
    }
    this.pages.add(pagesItem);
    return this;
  }

   /**
   * Get pages
   * @return pages
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PAGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<FormPage> getPages() {
    return pages;
  }


  public void setPages(List<FormPage> pages) {
    this.pages = pages;
  }


  public FormCapturePayload version(String version) {
    
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVersion() {
    return version;
  }


  public void setVersion(String version) {
    this.version = version;
  }


  public FormCapturePayload groupGuid(String groupGuid) {
    
    this.groupGuid = groupGuid;
    return this;
  }

   /**
   * Get groupGuid
   * @return groupGuid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_GROUP_GUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGroupGuid() {
    return groupGuid;
  }


  public void setGroupGuid(String groupGuid) {
    this.groupGuid = groupGuid;
  }


  public FormCapturePayload login(String login) {
    
    this.login = login;
    return this;
  }

   /**
   * Get login
   * @return login
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LOGIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLogin() {
    return login;
  }


  public void setLogin(String login) {
    this.login = login;
  }


  public FormCapturePayload skipText(String skipText) {
    
    this.skipText = skipText;
    return this;
  }

   /**
   * Get skipText
   * @return skipText
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SKIP_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSkipText() {
    return skipText;
  }


  public void setSkipText(String skipText) {
    this.skipText = skipText;
  }


  public FormCapturePayload orgGuid(String orgGuid) {
    
    this.orgGuid = orgGuid;
    return this;
  }

   /**
   * Get orgGuid
   * @return orgGuid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ORG_GUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOrgGuid() {
    return orgGuid;
  }


  public void setOrgGuid(String orgGuid) {
    this.orgGuid = orgGuid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FormCapturePayload formCapturePayload = (FormCapturePayload) o;
    return Objects.equals(this.submitText, formCapturePayload.submitText) &&
        Objects.equals(this.name, formCapturePayload.name) &&
        Objects.equals(this.responseStatus, formCapturePayload.responseStatus) &&
        Objects.equals(this.pages, formCapturePayload.pages) &&
        Objects.equals(this.version, formCapturePayload.version) &&
        Objects.equals(this.groupGuid, formCapturePayload.groupGuid) &&
        Objects.equals(this.login, formCapturePayload.login) &&
        Objects.equals(this.skipText, formCapturePayload.skipText) &&
        Objects.equals(this.orgGuid, formCapturePayload.orgGuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(submitText, name, responseStatus, pages, version, groupGuid, login, skipText, orgGuid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FormCapturePayload {\n");
    sb.append("    submitText: ").append(toIndentedString(submitText)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    responseStatus: ").append(toIndentedString(responseStatus)).append("\n");
    sb.append("    pages: ").append(toIndentedString(pages)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    groupGuid: ").append(toIndentedString(groupGuid)).append("\n");
    sb.append("    login: ").append(toIndentedString(login)).append("\n");
    sb.append("    skipText: ").append(toIndentedString(skipText)).append("\n");
    sb.append("    orgGuid: ").append(toIndentedString(orgGuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

