/*
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: api@bitly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bitly.model.V4;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * OrganizationAllOf
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-09-07T02:24:01.569+01:00[Europe/London]")
public class OrganizationAllOf {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_BSDS = "bsds";
  @SerializedName(SERIALIZED_NAME_BSDS)
  private List<String> bsds = null;

  public static final String SERIALIZED_NAME_CREATED = "created";
  @SerializedName(SERIALIZED_NAME_CREATED)
  private String created;

  public static final String SERIALIZED_NAME_IS_ACTIVE = "is_active";
  @SerializedName(SERIALIZED_NAME_IS_ACTIVE)
  private Boolean isActive;

  public static final String SERIALIZED_NAME_MODIFIED = "modified";
  @SerializedName(SERIALIZED_NAME_MODIFIED)
  private String modified;

  public static final String SERIALIZED_NAME_TIER_DISPLAY_NAME = "tier_display_name";
  @SerializedName(SERIALIZED_NAME_TIER_DISPLAY_NAME)
  private String tierDisplayName;

  public static final String SERIALIZED_NAME_TIER_FAMILY = "tier_family";
  @SerializedName(SERIALIZED_NAME_TIER_FAMILY)
  private String tierFamily;

  public static final String SERIALIZED_NAME_TIER = "tier";
  @SerializedName(SERIALIZED_NAME_TIER)
  private String tier;

  public static final String SERIALIZED_NAME_ROLE = "role";
  @SerializedName(SERIALIZED_NAME_ROLE)
  private String role;

  public static final String SERIALIZED_NAME_GUID = "guid";
  @SerializedName(SERIALIZED_NAME_GUID)
  private String guid;


  public OrganizationAllOf name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public OrganizationAllOf bsds(List<String> bsds) {
    
    this.bsds = bsds;
    return this;
  }

  public OrganizationAllOf addBsdsItem(String bsdsItem) {
    if (this.bsds == null) {
      this.bsds = new ArrayList<String>();
    }
    this.bsds.add(bsdsItem);
    return this;
  }

   /**
   * Get bsds
   * @return bsds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getBsds() {
    return bsds;
  }


  public void setBsds(List<String> bsds) {
    this.bsds = bsds;
  }


  public OrganizationAllOf created(String created) {
    
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCreated() {
    return created;
  }


  public void setCreated(String created) {
    this.created = created;
  }


  public OrganizationAllOf isActive(Boolean isActive) {
    
    this.isActive = isActive;
    return this;
  }

   /**
   * Get isActive
   * @return isActive
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsActive() {
    return isActive;
  }


  public void setIsActive(Boolean isActive) {
    this.isActive = isActive;
  }


  public OrganizationAllOf modified(String modified) {
    
    this.modified = modified;
    return this;
  }

   /**
   * Get modified
   * @return modified
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getModified() {
    return modified;
  }


  public void setModified(String modified) {
    this.modified = modified;
  }


  public OrganizationAllOf tierDisplayName(String tierDisplayName) {
    
    this.tierDisplayName = tierDisplayName;
    return this;
  }

   /**
   * Get tierDisplayName
   * @return tierDisplayName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTierDisplayName() {
    return tierDisplayName;
  }


  public void setTierDisplayName(String tierDisplayName) {
    this.tierDisplayName = tierDisplayName;
  }


  public OrganizationAllOf tierFamily(String tierFamily) {
    
    this.tierFamily = tierFamily;
    return this;
  }

   /**
   * Get tierFamily
   * @return tierFamily
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTierFamily() {
    return tierFamily;
  }


  public void setTierFamily(String tierFamily) {
    this.tierFamily = tierFamily;
  }


  public OrganizationAllOf tier(String tier) {
    
    this.tier = tier;
    return this;
  }

   /**
   * Get tier
   * @return tier
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTier() {
    return tier;
  }


  public void setTier(String tier) {
    this.tier = tier;
  }


  public OrganizationAllOf role(String role) {
    
    this.role = role;
    return this;
  }

   /**
   * Get role
   * @return role
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRole() {
    return role;
  }


  public void setRole(String role) {
    this.role = role;
  }


  public OrganizationAllOf guid(String guid) {
    
    this.guid = guid;
    return this;
  }

   /**
   * Get guid
   * @return guid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getGuid() {
    return guid;
  }


  public void setGuid(String guid) {
    this.guid = guid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrganizationAllOf organizationAllOf = (OrganizationAllOf) o;
    return Objects.equals(this.name, organizationAllOf.name) &&
        Objects.equals(this.bsds, organizationAllOf.bsds) &&
        Objects.equals(this.created, organizationAllOf.created) &&
        Objects.equals(this.isActive, organizationAllOf.isActive) &&
        Objects.equals(this.modified, organizationAllOf.modified) &&
        Objects.equals(this.tierDisplayName, organizationAllOf.tierDisplayName) &&
        Objects.equals(this.tierFamily, organizationAllOf.tierFamily) &&
        Objects.equals(this.tier, organizationAllOf.tier) &&
        Objects.equals(this.role, organizationAllOf.role) &&
        Objects.equals(this.guid, organizationAllOf.guid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, bsds, created, isActive, modified, tierDisplayName, tierFamily, tier, role, guid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrganizationAllOf {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    bsds: ").append(toIndentedString(bsds)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    tierDisplayName: ").append(toIndentedString(tierDisplayName)).append("\n");
    sb.append("    tierFamily: ").append(toIndentedString(tierFamily)).append("\n");
    sb.append("    tier: ").append(toIndentedString(tier)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    guid: ").append(toIndentedString(guid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

