/*
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: api@bitly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bitly.model.V4;

import java.util.Objects;
import java.util.Arrays;
import com.bitly.model.V4.PaymentInvoice;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * PaymentInvoices
 */
@JsonPropertyOrder({
  PaymentInvoices.JSON_PROPERTY_PAYMENT_INVOICES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-09-03T23:35:21.555+01:00[Europe/London]")
public class PaymentInvoices {
  public static final String JSON_PROPERTY_PAYMENT_INVOICES = "payment_invoices";
  private List<PaymentInvoice> paymentInvoices = null;


  public PaymentInvoices paymentInvoices(List<PaymentInvoice> paymentInvoices) {
    
    this.paymentInvoices = paymentInvoices;
    return this;
  }

  public PaymentInvoices addPaymentInvoicesItem(PaymentInvoice paymentInvoicesItem) {
    if (this.paymentInvoices == null) {
      this.paymentInvoices = new ArrayList<PaymentInvoice>();
    }
    this.paymentInvoices.add(paymentInvoicesItem);
    return this;
  }

   /**
   * Get paymentInvoices
   * @return paymentInvoices
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PAYMENT_INVOICES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PaymentInvoice> getPaymentInvoices() {
    return paymentInvoices;
  }


  public void setPaymentInvoices(List<PaymentInvoice> paymentInvoices) {
    this.paymentInvoices = paymentInvoices;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentInvoices paymentInvoices = (PaymentInvoices) o;
    return Objects.equals(this.paymentInvoices, paymentInvoices.paymentInvoices);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paymentInvoices);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentInvoices {\n");
    sb.append("    paymentInvoices: ").append(toIndentedString(paymentInvoices)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

