/*
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: api@bitly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bitly.model.V4;

import java.util.Objects;
import java.util.Arrays;
import com.bitly.model.V4.PlatformLimit;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * PlatformLimits
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-09-06T23:21:35.150+01:00[Europe/London]")
public class PlatformLimits {
  public static final String SERIALIZED_NAME_PLATFORM_LIMITS = "platform_limits";
  @SerializedName(SERIALIZED_NAME_PLATFORM_LIMITS)
  private List<PlatformLimit> platformLimits = null;


  public PlatformLimits platformLimits(List<PlatformLimit> platformLimits) {
    
    this.platformLimits = platformLimits;
    return this;
  }

  public PlatformLimits addPlatformLimitsItem(PlatformLimit platformLimitsItem) {
    if (this.platformLimits == null) {
      this.platformLimits = new ArrayList<PlatformLimit>();
    }
    this.platformLimits.add(platformLimitsItem);
    return this;
  }

   /**
   * Get platformLimits
   * @return platformLimits
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<PlatformLimit> getPlatformLimits() {
    return platformLimits;
  }


  public void setPlatformLimits(List<PlatformLimit> platformLimits) {
    this.platformLimits = platformLimits;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlatformLimits platformLimits = (PlatformLimits) o;
    return Objects.equals(this.platformLimits, platformLimits.platformLimits);
  }

  @Override
  public int hashCode() {
    return Objects.hash(platformLimits);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlatformLimits {\n");
    sb.append("    platformLimits: ").append(toIndentedString(platformLimits)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

